### ISSUE TITLE
Effect Handlers in OCaml

### ISSUE THREAD

**Issue by bluddy** [matijapretnar/eff#20]
Sorry for abusing the issue system for a question. Once effect handlers are implemented in OCaml, would it be possible to simply compile Eff to OCaml Lambda (using, for example, [Malfunction])(https://github.com/stedolan/malfunction), and let the runtime do the rest?

**Comment by matijapretnar** [comment]
Happy to answer the question here. No, it won't be as simple because the handlers that will be implemented in OCaml will have one-shot continuations (i.e. a continuation may be aborted or resumed at most once), whereas continuation use in Eff is unrestricted.

We have some current work in progress with Tom Schrijvers and Amr Hany Saleh from KU Leuven that allows you to translate Eff code into pure OCaml code by simulating effects using a free monad. Here, a native OCaml implementation of handlers would help us as we could translate handlers with one-shot continuations into native handlers, and keep the simulation for more complicated handlers.
